<?php
/**
 * @file
 * Install, update and uninstall functions
 */

function imageapi_optimize_uninstall() {
  $variable_names = array(
    'imageapi_optimize_service',
    'imageapi_optimize_toolkit',
    'imageapi_optimize_advpng',
    'imageapi_optimize_optipng',
    'imageapi_optimize_jpegtran',
    'imageapi_optimize_jfifremove',
    'imageapi_optimize_pngcrush',
  );
  foreach ($variable_names as $variable_name) {
    variable_del($variable_name);
  }
}
